[package]
name = "art3mis"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
starknet = "2.7.1"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.26.0" }
openzeppelin_testing = {path = "../cairo-contracts/packages/testing"}

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
